language: java
jdk:
  - openjdk8
  
sudo: required
script: ./mvnw clean install
  
notifications:
  email: rghorpade80@gmail.com

sudo: required
services:
  - docker

script:
 
   - docker build -t rghorpade80/travis-ci-game-of-life .
  

