language: java
jdk:
  - openjdk8
  
before_install:
  - chmod +x mvnw
script: ./mvnw clean install
  
notifications:
  email: rghorpade80@gmail.com

sudo: required
services:
  - docker

script:
 
   -  sudo docker build -t rghorpade80/travis-ci-game-of-life .
  

