language: java
jdk:
  - openjdk8
  
before_install:
  - chmod +x mvnw
script: ./mvnw clean install
  
notifications:
  email: rghorpade80@gmail.com

sudo: required
services:
  - docker

script:
 
   - docker build -t "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT} .
   - docker tag "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT}  "$DOCKER_USERNAME"/travis-ci-game-of-life:latest
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker push "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT}
   - docker push "$DOCKER_USERNAME"/travis-ci-game-of-life:latest
  

