dist: xenial
language: java
jdk:
- openjdk8
cache:
  directories:
  - "~/mycache"
  - "$HOME/.m2/repository"
before_install:
- chmod +x mvnw
install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.7/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
sudo: required
services:
- docker
jobs:
  include:
  - stage: BUILD MAVEN ARTIFACT
    script:
    - "./mvnw clean install -DskipTests"
    - cp ./gameoflife-web/target/gameoflife.war ~/mycache
    
  - stage: JUNIT TEST EXCUTION
    script:
    - "./mvnw test -B"
    
  - stage: NEXUS_ARTIFACT_PUSH
    script:
    - mvn deploy --settings travis.settings.xml
    on:
      branch: master
      
  - stage: BUILD & PUSH DOCKER IMAGE
    script:
    - cp ~/mycache/gameoflife.war .
    - docker build -t "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT} .
    - docker tag "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT}  "$DOCKER_USERNAME"/travis-ci-game-of-life:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "$DOCKER_USERNAME"/travis-ci-game-of-life:${TRAVIS_COMMIT}
    - docker push "$DOCKER_USERNAME"/travis-ci-game-of-life:latest
    
  #- stage: DEPLOY ON K8S CLUSTER
  #  script:
  #  - mkdir ${HOME}/.kube
  #  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
  #  - kubectl apply -f travis_ci_demo.yml
  
  
#deploy:
#  provider: script
 # script: mvn deploy --settings travis.settings.xml
 # on:
 #   branch: master
 
notifications:
  email: rghorpade80@gmail.com
env:
  global:
  - secure: ljYB4a7QEWzDLhxISuTHzUzFYjYy1sK31knYSZPD3limot/iTRtHh/j4IsrUi3esW3xpOmZdZgZ+qb1+wzSWbI4XFT6b2QcLD+2gEEf1u2WI+qvYMmhjw2oIT8lVMqh+nozvlx3kTPHU2TqKC2RslTxLqJuoa89U6xQ5oj8PepppNqxPJ9IxFvjDMMdS2CG5UJcuE/wwnNSvuPa2UTF86M5SEfB9P06XpHFK3WVo5pkZoOoqnO/Do0coxJBVk+jNqK+2PswKXkyCT5rSAjfT859kNSBpTqVwtyJGNUULO0AVOc2wVmLOCv+eZUeEwTVNpiuOC5H4GRUEY2xQcXXij+n5vhZwlcpTBlUYPuESR/VMHSRYGvmcVkTS9KIgeqoPkmnJ7XxJwKCzKwteBG2HFDm6otD5j1Z1vqFa1sV2wPu7v8l1mkcb2QmTX8VkwZV3yHzQadPQR1jo/ZnjxI3X2YbbGzTecuubYFqJgIXC7c4bYTVNLsfN5rattVurmA9I4Sw389iQWq45XHZQZ+nXye9mCh46kxVZrH3yRTNfJF6W4HAK1ncyb5WsRJHhPTzqzyB+hJG1ox7KW32Pm5LWq7PpVasm8YB2sBCPPFiMB3Y8FQHzMgU5gtDaJPq+M2V9zm1tOoet81JlN5QTK8/VpxDo54ck5VwtYoD8hYcWAic=
  - secure: lBWbEWuTSkuPj7uRopx2go1kjmJQoBNpzKvHWHeZzr54zv8ufHwyLKb6n8Ag03eR14cB8BCcbEvtQEXWK3663WdgYjxmWcwTISE/abB3TS+oOk4sj5F44mKKhri1pCQ3iw7uykQTX/FOIyutHi6nAY0eMoxK47CXcfA0mmb7UwRd8Y38wU0W3jN8Er2Z5dy0xC7pGlPTPlq4Z/Ddor0ELrNy9g+cKFM4QIz0JibJB3mINdSKV9I7Zhwbcdngw9esm2mVunR6WhKB9Z9kzYxmeTS8WF5m+MpgdhQT6elgHlkBwUOp4J44EuXhe3bYMagllOAGe29+8+9Rm1qQMlBDVEMgLojPPEEDMyTN1tfDzf7zE1q4N1D9fpnqvVNcKGQpcq5pBpDg4xAUUD+iKEXtySbY0edoLw+LsgQdsbXr8iUrGWaL1UHuF43GTBZiBGjSL9+ypvR0iP8fISF+FiMsZdErzqagCQ7gWFX3zUbe8IEBQJ9MKovN33j7qE2JBegW0IRqRXittB/JbhDe9MHXimTE54dfeHUjI6F7JqBkkOgmqgP0w2tswWYGavHwofr1JG0kiZSgmSLB2pRr8kae6ktLpn68dIWmCiTwJ7xcDfyHhHfHTfc+TdRtYd1Wj+5gZJ5GgJ81R/bTP9f+qOi+fO/IzLwm5nOJ3w1iSp6rL6Y=
